In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("datasets/flipkart_laptop_review_data.csv")

df

,Product Review ID,Title,rating,detail_review,upvote,downvote
0,3,Must buy!,5.0,Really usable one and value for money with all...,18,4
1,3,Terrific purchase,5.0,Product is Awesome ðŸ˜Ž ðŸ”¥But little Heating Probl...,23,11
2,4,Good quality product,4.0,I ordered Macbook Air - 8GB RAM and 512GB Sto...,32,31
3,4,Fabulous!,5.0,AwesomeREAD MORE,0,0
4,5,Absolute rubbish!,NaN,1 star rating is for Flipkart's smart upgrade ...,38,5
...,...,...,...,...,...,...
4144,670,Very poor,NaN,This machine is very slow and battery does not...,20,19
4145,670,Very poor,NaN,Battery Backup Is Worst It's 1.5 hour Only Bac...,6,4
4146,670,Hated it!,NaN,Extremely bad build and configuration assembly...,2,1
4147,670,Very poor,NaN,Battery backup very less. Some times system ha...,1,1
4148,670,Horrible,NaN,battery backup only 1.5 hours.READ MORE,8,7

In [4]:
df.isna().sum()

Product Review ID      0
Title                  0
rating               505
detail_review          0
upvote                 0
downvote               0
dtype: int64

In [5]:
df['rating'] = df['rating'].fillna(0)

In [6]:
df

,Product Review ID,Title,rating,detail_review,upvote,downvote
0,3,Must buy!,5.0,Really usable one and value for money with all...,18,4
1,3,Terrific purchase,5.0,Product is Awesome ðŸ˜Ž ðŸ”¥But little Heating Probl...,23,11
2,4,Good quality product,4.0,I ordered Macbook Air - 8GB RAM and 512GB Sto...,32,31
3,4,Fabulous!,5.0,AwesomeREAD MORE,0,0
4,5,Absolute rubbish!,0.0,1 star rating is for Flipkart's smart upgrade ...,38,5
...,...,...,...,...,...,...
4144,670,Very poor,0.0,This machine is very slow and battery does not...,20,19
4145,670,Very poor,0.0,Battery Backup Is Worst It's 1.5 hour Only Bac...,6,4
4146,670,Hated it!,0.0,Extremely bad build and configuration assembly...,2,1
4147,670,Very poor,0.0,Battery backup very less. Some times system ha...,1,1
4148,670,Horrible,0.0,battery backup only 1.5 hours.READ MORE,8,7

In [7]:
df.describe()

       Product Review ID       rating       upvote     downvote
count        4149.000000  4149.000000  4149.000000  4149.000000
mean          334.632683     4.052784    38.514582     7.941914
std           186.612538     1.619660    79.746979    16.221310
min             3.000000     0.000000     0.000000     0.000000
25%           182.000000     4.000000     5.000000     0.000000
50%           319.000000     5.000000    15.000000     2.000000
75%           500.000000     5.000000    46.000000     9.000000
max           670.000000     5.000000  1926.000000   385.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4149 entries, 0 to 4148
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product Review ID  4149 non-null   int64
 1   Title              4149 non-null   object
 2   rating             4149 non-null   float64
 3   detail_review      4149 non-null   object
 4   upvote             4149 non-null   int64
 5   downvote           4149 non-null   int64
dtypes: float64(1), int64(3), object(2)
memory usage: 194.6+ KB

In [10]:
df.to_csv("flipkart_laptop_review_cleaned_data.csv", index=False)

In [11]:
df

,Product Review ID,Title,rating,detail_review,upvote,downvote
0,3,Must buy!,5.0,Really usable one and value for money with all...,18,4
1,3,Terrific purchase,5.0,Product is Awesome ðŸ˜Ž ðŸ”¥But little Heating Probl...,23,11
2,4,Good quality product,4.0,I ordered Macbook Air - 8GB RAM and 512GB Sto...,32,31
3,4,Fabulous!,5.0,AwesomeREAD MORE,0,0
4,5,Absolute rubbish!,0.0,1 star rating is for Flipkart's smart upgrade ...,38,5
...,...,...,...,...,...,...
4144,670,Very poor,0.0,This machine is very slow and battery does not...,20,19
4145,670,Very poor,0.0,Battery Backup Is Worst It's 1.5 hour Only Bac...,6,4
4146,670,Hated it!,0.0,Extremely bad build and configuration assembly...,2,1
4147,670,Very poor,0.0,Battery backup very less. Some times system ha...,1,1
4148,670,Horrible,0.0,battery backup only 1.5 hours.READ MORE,8,7