# fp groth

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### get the data from data source

In [13]:
dataset = [
     ['E', 'A', 'D', 'B'],
    ['D', 'A', 'C', 'E', 'B'],
    ['C', 'A', 'B', 'E'],
    ['B', 'A', 'D'],
    ['D'],
    ['D', 'B'],
    ['A', 'D', 'E'],
    ['B', 'C']
]

### preprocessing the data

In [15]:
from mlxtend.preprocessing import TransactionEncoder

encoder = TransactionEncoder()

encoder.fit(dataset)

transformed_dataset = encoder.transform(dataset)

df_transormed = pd.DataFrame(transformed_dataset, columns=encoder.columns_)
df_transormed

       A      B      C      D      E
0   True   True  False   True   True
1   True   True   True   True   True
2   True   True   True  False   True
3   True   True  False   True  False
4  False  False  False   True  False
5  False   True  False   True  False
6   True  False  False   True   True
7  False   True   True  False  False

In [16]:
from mlxtend.frequent_patterns import fpgrowth
results = fpgrowth(df_transormed, use_colnames=True)
results

   support itemsets
0    0.750      (D)
1    0.750      (B)
2    0.625      (A)
3    0.500      (E)
4    0.500   (D, B)
5    0.500   (A, B)
6    0.500   (D, A)
7    0.500   (A, E)